name: secret testing

on: push

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Uses Secret
        run: echo "The secret is \${{ secrets.SECRET }}"
